---
name: workflow variables
on: push
env:
  PYTHON-VERSION: 3.9
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: setup python ${{env.PYTHON-VERSION}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON-VERSION}}
  job2:
    runs-on: ubuntu-latest
    env: null
    MYJOB-PYTHON-VERSION: 3.8
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: setup python ${{env.MYJOB-PYTHON-VERSION}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.MYJOB-PYTHON-VERSION}}
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: setup python
    env:
      MYSTEP-PYTHON-VERSION: 3.11
    uses: actions/setup-python@v5
    with:
      python-version: ${{env.MYSTEP-PYTHON-VERSION}}
